#설정 파일 , appliction.properties라는 파일이름으로도 할수있다.
#프로젝트를 처음 시작할때 SpringBoot에 의해서 apliciton.yml파일이 읽혀지고 이 안에 내용들을 가지고 환경 세팅을 한다.
#톰캣 서버의 포트번호를 8090으로 설정한것이다.
server:
  port: 8090

#==============================================================

#H2 Database설정
spring:
  h2:
    console:
      enabled: true
      #서버를 실행했을때 Http://localhost:8090/h2console
      #입력하면 서버에서 사용하고 있는 h2 데이터베이스에 접속 가능하다.
      path: /h2-console

  #h2 데이터베이스에대한 Driver을 사용한다.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    #JPA의해서 쿼리가 생성되어 만들어질때 H2데이터베이스 쿼리문을 사용해라 라는 의미이다.
    database-platform: org.hibernate.dialect.H2Dialect
    #console창에 쿼리가 만들어져서 보인다.
    show_sql: true
    #properties사용해서 쿼리문을 더 정돈된 상태로 만든다.
    properties:
      hibernate:
        format_sql: true





